# ========================================================
# | Author: Thomas (Liquid) Lundqvist
# | Server IP: play.kingconquest.eu
# | Website: www.kingconquest.eu
#========================================================
# |                                                      Information
# | ActiveWorlds:
# |  <World>: 								What worlds you want the plugin to be running on (name of World).
# |    General:
# |     <RespawnDelay>: 			Delay before you are respawned (seconds).
# |     <TeleportDelay>: 				Delay before you are teleported (seconds).
# |   Income:
# |     <CapCash>: 						Cash you are rewarded for capturing (instant and directly to the player).
# |    <IncomeDelay>: 				Time before Capital Rewards are devided out (minutes).
# |     <TownBaseValue>: 			Base value of Capturing a complete Objective.
# |     <VillageBaseValue>: 		Base value of Capturing a Beacon.
# |    Combat:
# |     <CaptureRate>:					Rate of which a player captures an objective (seconds)
# |     <CaptureDistance>:			Amount of Blocks away from the outpost you can be to capture it (X|Z).
# |     <CaptureAboveHeight>:	Amount of Blocks above the outpost you can be to capture it (Y).
# |     <CaptureBelowHeight>:	Amount of Blocks below the outpost you can be to capture it (Y).
# ========================================================
Database:
  Backend: FlatFile
  MySql:
    Host: localhost
    User: root
    Password: root
    Database: Conquest
    Port: 21
  SqlLite:
  FlatFile:
    AutoSaveInterval: 5 #Minutes
ActiveWorlds:
  world:
    General:
      Debug: false
      RespawnDelay: 10
      TeleportDelay: 10
    Income:
      CapCash: 30
      IncomeDelay: 60000
      TownBaseValue: 0.2
      VillageBaseValue: 0.5
    Combat:
      CaptureRate: 0.15
      CaptureDistance: 5.0
      CaptureMaxY: 5.0
      CaptureMinY: 1.0
  Sezty:
    General:
      Debug: false
      RespawnDelay: 10
      TeleportDelay: 10
    Income:
      CapCash: 30
      IncomeDelay: 60000
      TownBaseValue: 0.2
      VillageBaseValue: 0.5
    Combat:
      CaptureRate: 0.15
      CaptureDistance: 5.0
      CaptureMaxY: 5.0
      CaptureMinY: 1.0
